### ISSUE TITLE
esse projeto está ativo?

### ISSUE THREAD

**Issue by ghost** [GeorgiaPereira039/MemoriaGame#1]
Olá a todos.

esse projeto está ativo?

*gostaria de contribuir com algumas ideias*

**Comment by GeorgiaPereira039** [comment]
Olá, esta sim... Por favor, vou ficar muito feliz com sua contribuição :)

Em qui., 29 de dez. de 2022 18:11, Code Hangen ***@***.***>
escreveu:

**Comment by ghost** [comment]
Oi GeorgiaPereira039.

> Olá, esta sim... Por favor, vou ficar muito feliz com sua contribuição :)

fico feliz por seu feedback e vou ver como posso contribuir muito aqui. tenho várias ideias interessantes e espero ajudar de alguma forma. vou fechar essa issue, e obrigado pela resposta motivadora.

**Comment by GeorgiaPereira039** [comment]
Eu que agradeço pela contribuição. Vai dar td certo ☺

Em sex., 6 de jan. de 2023 18:35, Code Hangen ***@***.***>
escreveu:

**Comment by ghost** [comment]
Oi GeorgiaPereira039.

> Eu que agradeço pela contribuição. Vai dar td certo relaxed

valeu pelo comentário, uma ideia que tive seria ter 2 versões: mobile e desktop. *O que você pensa  ou acha da ideia de ter uma versão mobile e uma versão em desktop? (quero escutar sua opinião)*

**Comment by GeorgiaPereira039** [comment]
Você chegou a testar o jogo no celular?

Em sex., 6 de jan. de 2023 19:46, Code Hangen ***@***.***>
escreveu:

**Comment by ghost** [comment]
> Você chegou a testar o jogo no celular?

- testei e achei daora. 
- mas minha ideia geral, era que estava pensando em desenvolver algo nativamente, algo no react-native ou no onsen-ui - ambos frameworks precisam apenas de html, css. 
- outro argumento principal para essa feature(onsen-ui ou react-native) seria que adicionar maior extensibilidade ao jogo, por exemplo - a maior parte dos jogos é feita com algum mecanismo ou motor de jogo como construct2, unity, rpg maker etc. porém não existe extensibilidade, ou seja, você fica preso em algum mecanismo ou motor de jogo.
- por outro lado, com apenas html, css e js você tem maior suporte a sistemas operacionais modernos como windows, linux, macOS etc. porém, apesar disso você não tem extensibilidade. Haja vista que precisaria de ter o conhecimento em html, css, js. 
- para resolver esse problema, cada desenvolvedor poderia implementar novas funcionalidades de acordo com seu framework favorito. O que contribui para a extensibilidade que comentei anteriormente.
- outro argumento interessante para a versão mobile, é que é mais "performático". haja vista que você não precisa ler totalmente html, css, js ou ter um navegador para jogar. O que contribui de certa forma para o jogo ser mais rápido para usuários.
- uma vantagem inicial é que a maior parte de frameworks para desenvolvimento mobile já vem pré-configurado com algum guia de design para melhor layout, o que pode contribuir com a jogabilidade do jogo.

**Comment by GeorgiaPereira039** [comment]
Que bacana que testou.... Então tentei fazer algo respondido para se
adequar ao celular tbm.... Mas não funciona em todos.
Ainda não estou boa o suficiente...

Então mas penso sim fazer outras versões, colocar um sistema de rank e
vários níveis.

Ah sim bacana entendi sua ideia...

Em sex., 6 de jan. de 2023 19:56, Code Hangen ***@***.***>
escreveu:

**Comment by ghost** [comment]
Oi GeorgiaPereira039.

> Que bacana que testou.... Então tentei fazer algo respondido para se
adequar ao celular tbm.... Mas não funciona em todos.
> Ainda não estou boa o suficiente...
> Então mas penso sim fazer outras versões, colocar um sistema de rank e
> vários níveis.
> Ah sim bacana entendi sua ideia...
 
valeu pelo comentário, segue outra ideia. outra ideia complementar que pensei, seria adicionar uma documentação técnica, caso as pessoas queiram adicionar outras figurinhas ou saber como funciona, como foi desenvolvido. 

*O que você pensa ou acha dessa nova ideia de adicionar documentação para facilitar maior suporte ao jogo, conhecimento ao usuário?*

- além da ideia, gostaria de adicionar uma música de fundo, geralmente em jogos existe alguma música interessante em um plano de fundo tocando.

**Comment by GeorgiaPereira039** [comment]
Acho interessante o sistema de figurinhas. Pode ter algo de recompensa tbm.
Um álbum Virtual

Em sex., 6 de jan. de 2023 20:06, Code Hangen ***@***.***>
escreveu:

**Comment by ghost** [comment]
> Acho interessante o sistema de figurinhas. Pode ter algo de recompensa tbm.
> Um álbum Virtual

Uma das dificuldades quando você fica mais velho ou uma pessoa mais idosa é a dificuldade em lembrar de coisas como data de aniversário, a lembrança de alguma pessoa querida. Porém, há casos que a dificuldade é alguma lembrança em geral como o lugar ou a comida que você mais gosta também. 

Recentemente, li uma reportagem que disse que os jogos de memória podem ajudar na memorização de pessoas idosas ou que tem/possuem dificuldade de certa forma com memorização. 

Nesse sentido, o que você falou pode ser de grande ajuda. Podemos ter quem sabe um álbum virtual onde algum familiar insere o álbum de fotos de sua família e a pessoa idosa vai tentando jogar o jogo de memória e com isso pode aos poucos ajudando na memorização? 

- Sei que esse processo não é 100% viavel a maior parte dos casos, mas pode ajudar de alguma forma. Esse 100% é apenas um chute, eu teria que fazer alguma pesquisa ou ter algum dado sobre isso.*
- Essa ideia que tive agora foi em relação a pesquisa que estava fazendo(por exemplo, pesquisei muito a questão de jogos, questões da razão dos jogos serem importantes para a maior parte das pessoas. Além disso, como os jogos podem ajudar as pessoas que precisam de alguma ajuda, apoio emocional ou ponto de fuga ou partida para ter um ambiente mais agradável ou seguro.), a reportagem que li e seu feedback.

*O que você pensa ou acha dessa ideia?*
- caso haja interesse nessas ideias posso enviar um pull request e farei o fork ainda hoje.

**Comment by GeorgiaPereira039** [comment]
Bacana... Eu conversei com uma colega de faculdade sobre isso a um tempo
atrás. Sobre como os jogos podem ajudar.
Eu mesma quando fico muito ansiosa paro para relaxar e jogar

Em sex., 6 de jan. de 2023 20:22, Code Hangen ***@***.***>
escreveu:

**Comment by ghost** [comment]
Oi GeorgiaPereira039.

> Bacana... Eu conversei com uma colega de faculdade sobre isso a um tempo
> atrás. Sobre como os jogos podem ajudar.
> Eu mesma quando fico muito ansiosa paro para relaxar e jogar

Tenho a permissão, concessão, apoio ou mesmo direito seu para fazer um fork e enviar o pull-request hoje? 

pergunto sobre isso, pois caso haja interesse nessas ideias posso enviar um pull-request e farei o fork ainda hoje. 

além disso, gostaria da sua confirmação para fazer isso *(criar um pull-request com essas ideias caso queira e ache que é algo interessante, relevante ou importante)*

**Comment by GeorgiaPereira039** [comment]
Pode fazer sim!! ;)

Em sex., 6 de jan. de 2023 20:43, Code Hangen ***@***.***>
escreveu:

**Comment by ghost** [comment]
Oi GeorgiaPereira039.

> Pode fazer sim!! ;)

valeu pelo comentário.
