### ISSUE TITLE
ideias complementares para melhorar o jogo ou tentar melhorar o jogo

### ISSUE THREAD

**Issue by ghost** [GeorgiaPereira039/MemoriaGame#18]
Oi GeorgiaPereira039.

Gostaria de saber aqui se possível outras ideias complementares para melhorar o jogo:

1. memoriagame em cdn: geralmente arquivos estáticos em jogos ficam numa rede cdn(content-delivery-networking), isso permite que o arquivo seja carregado mais rápido. Geralmente, você cria um repositório de arquivos estáticos e sincroniza em alguma empresa, plataforma para isso. Por exemplo, suponhamos que seria algo como:
    - `<link href="https://cdn.jsdelivr.net/npm/memoriagame@5.3.0-alpha1/dist/css/memoriagame.css" rel="stylesheet" integrity="sha384-add" crossorigin="anonymous">`
    - `<link href="https://cdn.jsdelivr.net/npm/memoriagame@5.3.0-alpha1/dist/css/rating-stars.css" rel="stylesheet" integrity="sha384-add" crossorigin="anonymous">`
    - `<script src="https://cdn.jsdelivr.net/npm/memoriagame@5.3.0-alpha1/dist/js/memoriagame.js" integrity="sha384-add" crossorigin="anonymous"></script>`

*Outra vantagem inicial é se o jogo for online mesmo, faria sentido pensar em distribuir esses arquivos em uma rede do tipo cdn, já que é algo comum na maior parte dos casos. Além disso, outro argumento complementar seria que isso permite por exemplo que um ou mais arquivos fiquem isolados e não num mesmo projeto. Nesse caso, você fica focado mais na parte estrutural ou lógica do projeto separando um certo nível arquivos estáticos, o que de certo um ou mais projetos fazem seja em sites ou jogos para uma melhor organização visual e de código.*

***(exemplo prático)***
```html
<!DOCTYPE html>
<html lang="pt-BR">
   <head>
      <meta charset="UTF-8">
      <meta  name="viewport" content="" content="width=device-width, initial-scale=1.0">
      <link href="https://cdn.jsdelivr.net/npm/memoriagame@5.3.0-alpha1/dist/css/jmemori.css" rel="stylesheet" type="text/css" integrity="sha384-add" crossorigin="anonymous" defer/>
      <script src="https://cdn.jsdelivr.net/npm/memoriagame@5.3.0-alpha1/dist/js/memoria.js" integrity="sha384-add" crossorigin="anonymous" defer></script>
      <link href="https://cdn.jsdelivr.net/npm/memoriagame@5.3.0-alpha1/dist/css/rating-stars.css" rel="stylesheet" type="text/css" integrity="sha384-add" crossorigin="anonymous" defer/>
      <title>Jogo da Memória</title>
   </head>
   <body>
      <h1> Jogo da Memória</h1>
      <img id="squirtle" src="https://cdn.jsdelivr.net/npm/memoriagame@5.3.0-alpha1/dist/img/squirtle.png" alt="squirtle icon">
      <img id="togepi" src="https://cdn.jsdelivr.net/npm/memoriagame@5.3.0-alpha1/dist/img/togeppi.png" alt="togepi icon">
      <img id="eve" src="https://cdn.jsdelivr.net/npm/memoriagame@5.3.0-alpha1/dist/img/eve.png" alt="eve icon">
      <img id="chikorita" src="https://cdn.jsdelivr.net/npm/memoriagame@5.3.0-alpha1/dist/img/chikorita.png" alt="chikorita icon">
      <div class="rating-stars">
         <input type="radio" name="rating" id="rs0" checked><label for="rs0"></label>
         <input type="radio" name="rating" id="rs1"><label for="rs1"></label>
         <input type="radio" name="rating" id="rs2"><label for="rs2"></label>
         <input type="radio" name="rating" id="rs3"><label for="rs3"></label>
         <input type="radio" name="rating" id="rs4"><label for="rs4"></label>
         <input type="radio" name="rating" id="rs5"><label for="rs5"></label>
         <span class="rating-counter"></span>
      </div>
      <main>
         <div class="tabuleiro"></div>
         <button id="btnRestart" onclick="restart()">Jogar Novamente</button>
         <footer>
            <p>Georgia S Pereira, MemoryGame, 2022 &copy;</p>
         </footer>
      </main>
      <div class="audio">
         <audio controls loop autoplay>
         <source src="./css/tema.mp3" type="audio/mp3">
      </div>
   </body>
</html>
```

2. memoriagame em git modules: quando você gerencia muito código, pode ser que um ou mais projetos tenha alguma base de código. Existem submódulos git que você pode compartilhar código para múltiplos projetos ao mesmo tempo. Segue um exemplo:
```javascript
// arquivo .gitmodules
[submodule "docs"]
	path = docs/documentacao
	url = git://github.com/GeorgiaPereira039/MemoriaGame.git
[submodule "css"]
	path = css/styles
	url = git://github.com/GeorgiaPereira039/MemoriaGame.git
```

3. memoriagame em web component: Existe um padrão chamado "web-component" - a ideia central é criar componentes da web reutilizáveis, então você pode utilizar a mesma estrutura css, js e html e modificar ou distribuir da forma como queira.

```html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Memoriagame</title>
    <!-- Imports polyfill -->
    <script src="../webcomponentsjs/webcomponents.min.js"></script>
    <!-- Imports custom element -->
    <link rel="import" href="memoriagame.html">
    <link rel="import" href="rating-stars.html">
</head>
<body>
    <!-- adicionar custom element -->
    <rating-stars></rating-stars>
    <!-- adicionar custom element -->
    <memoriagame></memoriagame>
</body>
</html>
```

4. adicionar link do jogo na barra lateral do GitHub: algo que percebi é que não existe um link na página do repositório para o jogo.
![image](https://user-images.githubusercontent.com/111701513/211397581-831887c7-946b-453e-90fb-406db240a8b0.png)

5. criar discussões sobre o jogo: por exemplo, em vez de criar issues, existem coisas como GitHub Discussions onde você pode discutir sobre qual feature ou quais features são mais ou menos importantes para serem lançadas do que criar issue específica para isso. Algo como: `https://github.com/GeorgiaPereira039/MemoriaGame/discussions`

![image](https://user-images.githubusercontent.com/111701513/211403590-9faa1274-d6cf-4b6e-8ab6-1b2251062f20.png)

*O que você pensa ou acha sobre essas novas ideias? (essas foram minhas últimas ideias para melhorar ou tentar melhorar o jogo, é muito importante sua opinião)*

**Comment by GeorgiaPereira039** [comment]
Olá b dia tudo bem?
Muito bacana suas ideias, vejo que tem grande potencial, coisas que da para
aplicar e trabalhar sim.
Sobre o link vou ver depois

Em ter., 10 de jan. de 2023 17:21, Code Hangen ***@***.***>
escreveu:

**Comment by ghost** [comment]
Oi GeorgiaPereira039.

> Muito bacana suas ideias, vejo que tem grande potencial, coisas que da para
> aplicar e trabalhar sim.
> Sobre o link vou ver depois

obrigado pelo comentário. conseguir completar as tarefas que prometi, vou enviar hoje o pull request final - espero ajudar e contribuir com esse repositório.
