### ISSUE TITLE
lista de entregas de recursos para o jogo MemoriaGame

### ISSUE THREAD

**Issue by ghost** [GeorgiaPereira039/MemoriaGame#5]
Oi.

Por favor, acessa esse link e vê o que você acha: `https://georgiapereira039.github.io/MemoriaGame/docs/#/`

*Você irá ver algo mais ou menos assim em mobile ou em um ou mais dispositivos:*
<img src="https://user-images.githubusercontent.com/111701513/211658038-537fa601-08e6-4ced-a487-2d57b06a6281.png" id="image" width="690px"/>

*ou pode visualizar uma demonstração em protótipo aqui*
url: `https://docsify-this.net/?basePath=https://raw.githubusercontent.com/GeorgiaPereira039/MemoriaGame/main#/`

***atualização**
o que foi feito/ e o que faltava - mas foi concluído:
- [x] pasta e arquivos para a documentação técnica
- [x] link da documentação técnica
- [x] a versão mobile em onsen-ui ***implementar***
- [x] álbum virtual ***implementar***
- [x] sistema de rank ***em fase de conceito***
- [x] salvar ranking
- [x] vários níveis ****em fase de conceito***
- [x] selecionar outras música de fundo ***não implementar, pode ser complexo***

**Comment by GeorgiaPereira039** [comment]
Ficou perfeito. Achei bacana o menu e as abas inseridas antes de iniciar o
jogo

Em dom., 8 de jan. de 2023 às 15:07, Code Hangen ***@***.***>
escreveu:

**Comment by GeorgiaPereira039** [comment]
você fez um bom trabalho!

Em dom., 8 de jan. de 2023 às 15:14, Georgia Silva ***@***.***>
escreveu:

**Comment by ghost** [comment]
Oi GeorgiaPereira039.

> você fez um bom trabalho!

valeu pelo feedback.

> Ficou perfeito. Achei bacana o menu e as abas inseridas antes de iniciar o
> jogo

valeu pelo feedback. Agora vou ver se desenvolvo os outros recursos que listei e envio um pull-request.

**Comment by GeorgiaPereira039** [comment]
Show!

Em dom., 8 de jan. de 2023 15:16, Code Hangen ***@***.***>
escreveu:

**Comment by GeorgiaPereira039** [comment]
qualquer coisa me chame no linkedin
https://www.linkedin.com/in/georgia-pereira-1151bb133
ou no zap 11967875799

Em dom., 8 de jan. de 2023 às 15:16, Code Hangen ***@***.***>
escreveu:

**Comment by ghost** [comment]
Oi GeorgiaPereira039.

> qualquer coisa me chame no linkedin
> https://www.linkedin.com/in/georgia-pereira-1151bb133
> ou no zap 11967875799

valeu pela informação.

> Show!

Uma ideia interessante seria adicionar uma url personalizada para o jogo, exemplo: `https://memoriagame.github.io/`

atualmente não existe uma organização no GitHub. Nesse sentido, podemos criar uma organização personalizada e inserir repositórios separados como: documentação técnica, versão web e versão mobile. Isso permite maior auditabilidade do código.

O que você pensa sobre a ideia de criar uma organização ou comunidade para o jogo de memória ou url personalizada para o jogo no GitHub Pages?

*ideia*
- `https://github.com/memoriagame` -> organização/comunidade do jogo de memoria: memoriagame
- `https://memoriagame.github.io/` -> homepage
- `https://memoriagame.github.io/docs/#/` -> documentação técnica
- `https://memoriagame.github.io/web` -> versão web do jogo
- `https://memoriagame.github.io/mobile/` -> versão do jogo mobile

**Comment by GeorgiaPereira039** [comment]
Eu não tenho muitos pensamentos sobre isso, pois no momento vão em
desencontro com o que desejo... Mas fique a vontade para fazer se quiser

Em dom., 8 de jan. de 2023 15:30, Code Hangen ***@***.***>
escreveu:

**Comment by ghost** [comment]
Oi GeorgiaPereira039.

> Eu não tenho muitos pensamentos sobre isso, pois no momento vão em
> desencontro com o que desejo... Mas fique a vontade para fazer se quiser

tudo bem então, não farei porque não é algo interessante e relevante aqui.  Novamente, valeu pelo feedback. Vou desenvolver os recursos que listei então.

**Comment by GeorgiaPereira039** [comment]
Ok! Combinado

Em dom., 8 de jan. de 2023 15:39, Code Hangen ***@***.***>
escreveu:

**Comment by ghost** [comment]
Oi GeorgiaPereira039.

> Ok! Combinado

Sobre o sistema de ranking pensei em algo assim:

![image](https://user-images.githubusercontent.com/111701513/211213372-b8c00633-026a-4d1c-bc73-7b900db7dcb8.png)

*O que você acha ou pensa sobre esse layout de ranking feito com html, css? é uma ideia boa ou ruim?*

*ideia*
- a medida que alguma pessoa acerta o jogo, a estrela fica com a cor amarela e a medida que perde a estrela fica vazia.

**Comment by GeorgiaPereira039** [comment]
Ótimo!  Que topop... Gostei

Em dom., 8 de jan. de 2023 15:46, Code Hangen ***@***.***>
escreveu:

**Comment by ghost** [comment]
Oi GeorgiaPereira039.

> Ótimo!  Que topop... Gostei

valeu pelo feedback. Uma ideia que tive, seria sobre a ideia de vários níveis e álbum de fotos/figurinhas acho que isso pode ser feito da seguinte forma:
- uma ou mais pessoas escolhem se vão jogar de acordo com o tema do jogo ou se vão escolher importar um álbum de fotos, figurinhas para jogar. Dessa forma temos dois níveis iniciais, um feito a partir do próprio jogo e outro feito a partir do usuário.

*O que você acha ou pensa sobre a ideia de unir dois recursos em algo único, algo integrado?*
![image](https://user-images.githubusercontent.com/111701513/211214228-1f291579-2a48-445f-afd8-83fd6e296516.png)

*Como podemos ver nessa imagem conceitual existem 2 tipos de jogo: jogar normal, onde existe a fase de pokemon e o jogar diferenciado, onde a pessoa que vai jogar escolhe o álbum de fotos ou figurinhas para o jogo de memória*

**Comment by GeorgiaPereira039** [comment]
Pensei nisso tbm em fazer por tema, colocar os elementos de ca cada pokemon

Em dom., 8 de jan. de 2023 15:52, Code Hangen ***@***.***>
escreveu:

**Comment by ghost** [comment]
Oi GeorgiaPereira039.

> Pensei nisso tbm em fazer por tema, colocar os elementos de ca cada pokemon

podemos utilizar isso de forma randômica, aleatória.  por exemplo, vamos imaginar que cada figura representa um tipo de fase. Abaixo temos algo que explica isso conceitualmente:

*fase 1*
<img src="https://user-images.githubusercontent.com/104602308/188720398-868da1fd-1edf-4e46-ad17-d5548a8aaec6.png"/>
*fase 2*
<img src="https://user-images.githubusercontent.com/104602308/188720434-a6bf04d1-0b6f-454a-a957-e00bb5e3a9d4.png"/>
*fase 3*
<img src="https://user-images.githubusercontent.com/104602308/188720285-a221ecb7-3274-45e0-a064-2a0e6dd49ae4.png"/>
*fase 4*
<img src="https://user-images.githubusercontent.com/104602308/188720691-9f0be836-c2a1-4bb2-ad02-3fad934d8f5e.png"/>
*fase 5*
<img src="https://user-images.githubusercontent.com/104602308/188720553-8a95c9b9-4a4d-476b-bf54-a4de43ec2c15.png"/>
*fase 6*
<img src="https://user-images.githubusercontent.com/104602308/188720605-16b46433-f84d-472a-ae49-3e391a3c62bb.png"/>
*fase 7*
<img src="https://user-images.githubusercontent.com/104602308/188720463-64fc8a5e-b058-4848-8777-9639f7a6acbe.png"/>

*veja que cada vez que a página é carregada ou alguém clica em jogar novamente a imagem do card na parte frontal muda de forma aleatória. então da fase 1 até a fase 7, as figuras mudam de forma aleatória.*

*O que você acha ou pensa dessa ideia?*

**Comment by GeorgiaPereira039** [comment]
Se precisar de ajuda com algo me avisa

Em dom., 8 de jan. de 2023 16:27, Georgia Silva ***@***.***>
escreveu:

**Comment by ghost** [comment]
Oi GeorgiaPereira039.

> Se precisar de ajuda com algo me avisa

- valeu pelo feedback
- vou ver se envio ainda hoje o restante do código. já tenho o código do rank funcionando, falta só dar uma opção/feature para salvar onde a pessoa está dentro do jogo. Inicialmente, penso em utilizar o armazenamento local como local-storage para configurar um ponto onde a pessoa estava antes da página ser recarregada ou quando é carregada.

**Comment by GeorgiaPereira039** [comment]
Eu tinha pensado em algo estático onde a pessoa escolhia.... Mas randômico
fica melhor..
Vai gerar mais anseio na pessoa em jogar e em querer ver as próximas fases

Em dom., 8 de jan. de 2023 19:26, Code Hangen ***@***.***>
escreveu:

**Comment by ghost** [comment]
Oi GeorgiaPereira039.

> Eu tinha pensado em algo estático onde a pessoa escolhia.... Mas randômico
> fica melhor..
> Vai gerar mais anseio na pessoa em jogar e em querer ver as próximas fases

isso é interessante? você acha que isso pode ou é interessante? *gostaria de uma confirmação se a ideia é boa ou ruim, falo disso, pois não entendi o que você disse em relação a ansiedade ao jogar esse jogo. não entendi se a ansiedade pelo jogo seria algo bom ou ruim*

**Comment by GeorgiaPereira039** [comment]
Boa

Em dom., 8 de jan. de 2023 20:29, Code Hangen ***@***.***>
escreveu:

**Comment by ghost** [comment]
Oi GeorgiaPereira039.

> Boa

valeu pelo feedback. 

*Uma dúvida posso fechar essa issue? A entrega foi feita com sucesso?*

**atualização** fechei a issue sem querer.
